CLASSES_TR = {
    'apple': 'elma',
    'aquarium_fish': 'akvaryum balığı',
    'baby': 'bebek',
    'bear': 'ayı',
    'beaver': 'kunduz',
    'bed': 'yatak',
    'bee': 'arı',
    'beetle': 'böcek',
    'bicycle': 'bisiklet',
    'bottle': 'şişe',
    'bowl': 'kase',
    'boy': 'erkek çocuk',
    'bridge': 'köprü',
    'bus': 'otobüs',
    'butterfly': 'kelebek',
    'camel': 'deve',
    'can': 'kutu',
    'castle': 'şato',
    'caterpillar': 'tırtıl',
    'cattle': 'sığır',
    'chair': 'sandalye',
    'chimpanzee': 'şempanze',
    'clock': 'saat',
    'cloud': 'bulut',
    'cockroach': 'hamam böceği',
    'couch': 'kanepe',
    'crab': 'yengeç',
    'crocodile': 'timsah',
    'cup': 'fincan',
    'dinosaur': 'dinozor',
    'dolphin': 'yunus',
    'elephant': 'fil',
    'flatfish': 'yassı balık',
    'forest': 'orman',
    'fox': 'tilki',
    'girl': 'kız çocuk',
    'hamster': 'hamster',
    'house': 'ev',
    'kangaroo': 'kanguru',
    'keyboard': 'klavye',
    'lamp': 'lamba',
    'lawn_mower': 'çim biçme makinesi',
    'leopard': 'leopar',
    'lion': 'aslan',
    'lizard': 'kertenkele',
    'lobster': 'ıstakoz',
    'man': 'adam',
    'maple_tree': 'akçaağaç',
    'motorcycle': 'motosiklet',
    'mountain': 'dağ',
    'mouse': 'fare',
    'mushroom': 'mantar',
    'oak_tree': 'meşe ağacı',
    'orange': 'portakal',
    'orchid': 'orkide',
    'otter': 'su samuru',
    'palm_tree': 'palmiye ağacı',
    'pear': 'armut',
    'pickup_truck': 'pikap kamyonet',
    'pine_tree': 'çam ağacı',
    'plain': 'ova',
    'plate': 'tabak',
    'poppy': 'haşhaş',
    'porcupine': 'dikenli kirpi',
    'possum': 'opossum',
    'rabbit': 'tavşan',
    'raccoon': 'rakun',
    'ray': 'vatoz',
    'road': 'yol',
    'rocket': 'roket',
    'rose': 'gül',
    'sea': 'deniz',
    'seal': 'fok balığı',
    'shark': 'köpekbalığı',
    'shrew': 'şirin fare',
    'skunk': 'kokarca',
    'skyscraper': 'gökdelen',
    'snail': 'salyangoz',
    'snake': 'yılan',
    'spider': 'örümcek',
    'squirrel': 'sincap',
    'streetcar': 'tramvay',
    'sunflower': 'ayçiçeği',
    'sweet_pepper': 'dolmalık biber',
    'table': 'masa',
    'tank': 'tank',
    'telephone': 'telefon',
    'television': 'televizyon',
    'tiger': 'kaplan',
    'tractor': 'traktör',
    'train': 'tren',
    'trout': 'alabalık',
    'tulip': 'lale',
    'turtle': 'kaplumbağa',
    'wardrobe': 'gardırop',
    'whale': 'balina',
    'willow_tree': 'söğüt ağacı',
    'wolf': 'kurt',
    'woman': 'kadın',
    'worm': 'solucan'
}
